#spring.application.name=JournalApp
#server.port=8082
#
#spring.data.mongodb.uri=mongodb+srv://divyansh07020_db_user:Zy034t9L6Byj59b4@cluster0.zoaol10.mongodb.net/journaldb?retryWrites=true&w=majority
##spring.data.mongodb.host=localhost
##spring.data.mongodb.port=27017
##spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true